package com.particlephysics.physics;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * Particle decay with exact two body kinematics and realistic three body spectra.
 *
 * <p>Every decay conserves energy and momentum: two body decays are solved analytically, three body
 * decays are generated by first sampling the lepton energy from the measured spectrum and then
 * decaying the recoiling neutrino system isotropically, which reproduces the correct neutrino mass
 * distribution.
 */
public final class Decays {
    private Decays() {
    }

    /** One decay product with its laboratory energy and momentum vector. */
    public record Product(ParticleSpecies species, double energyMeV, Vec3 momentum) {
        public double momentumMagnitude() {
            return momentum.length();
        }
    }

    /**
     * Decays a particle. Returns an empty list for stable particles.
     *
     * @param species   the decaying species
     * @param energyMeV kinetic energy in the laboratory
     * @param direction unit direction of flight
     */
    public static List<Product> decay(ParticleSpecies species, double energyMeV, Vec3 direction,
                                      Random random) {
        List<Product> products = new ArrayList<>(3);
        if (species.isStable()) {
            return products;
        }
        switch (species) {
            case NEUTRON, ANTINEUTRON -> betaDecay(species, energyMeV, direction, random, products);
            case MUON, ANTIMUON -> michelDecay(energyMeV, direction, random, products);
            case PION_PLUS, PION_MINUS -> twoBody(species, energyMeV, direction, random,
                    Units.PION_CHARGED_MASS, species == ParticleSpecies.PION_PLUS
                            ? ParticleSpecies.ANTIMUON : ParticleSpecies.MUON, products);
            case PION_NEUTRAL -> twoBody(species, energyMeV, direction, random,
                    Units.PION_NEUTRAL_MASS, ParticleSpecies.PHOTON, products);
            case KAON_PLUS, KAON_MINUS -> kaonDecay(species, energyMeV, direction, random, products);
            case KAON_NEUTRAL -> twoBody(species, energyMeV, direction, random,
                    Units.KAON_NEUTRAL_MASS, ParticleSpecies.PION_PLUS, products);
            case URANIUM238 -> twoBody(species, energyMeV, direction, random, 221694.9,
                    ParticleSpecies.ALPHA, products);
            default -> {
                // stable species are handled above; anything else decays to two photons so that
                // no energy silently disappears
                twoBody(species, energyMeV, direction, random, Math.max(1.0, species.mass()),
                        ParticleSpecies.PHOTON, products);
            }
        }
        return products;
    }

    /**
     * Solves a two body decay. The second daughter carries the recoil momentum, so the total
     * four-momentum is conserved exactly.
     */
    public static void twoBody(ParticleSpecies parent, double kineticMeV, Vec3 direction,
                               Random random, double parentMass,
                               ParticleSpecies daughterA, List<Product> out) {
        ParticleSpecies daughterB = recoilPartner(parent, daughterA);
        double massA = daughterA.mass();
        double massB = daughterB.mass();
        if (parentMass < massA + massB) {
            parentMass = massA + massB;
        }
        double totalEnergy = kineticMeV + parentMass;
        double momentum = Math.sqrt(Math.max(0.0, totalEnergy * totalEnergy - parentMass * parentMass));
        double gamma = totalEnergy / parentMass;
        double beta = Relativity.clampBeta(momentum / totalEnergy);

        double energyAStar = (parentMass * parentMass + massA * massA - massB * massB)
                / (2.0 * parentMass);
        double momentumStar = Math.sqrt(Math.max(0.0, energyAStar * energyAStar - massA * massA));

        double cosTheta = random.nextDouble() * 2.0 - 1.0;
        double sinTheta = Math.sqrt(Math.max(0.0, 1.0 - cosTheta * cosTheta));
        double phi = random.nextDouble() * Math.PI * 2.0;

        Vec3 tangent = direction.normalise();
        Vec3[] basis = orthonormalBasis(tangent);
        Vec3 perpendicular = basis[0].scale(Math.cos(phi)).add(basis[1].scale(Math.sin(phi)));

        // daughter A
        double parallelA = gamma * (momentumStar * cosTheta + beta * energyAStar);
        double perpA = momentumStar * sinTheta;
        Vec3 momentumA = tangent.scale(parallelA).add(perpendicular.scale(perpA));
        double energyALab = gamma * (energyAStar + beta * momentumStar * cosTheta);
        out.add(new Product(daughterA, Math.max(0.0, energyALab - massA), momentumA));

        // daughter B carries the remaining momentum exactly
        Vec3 momentumB = tangent.scale(momentum - parallelA).subtract(perpendicular.scale(perpA));
        double energyBLab = totalEnergy - energyALab;
        out.add(new Product(daughterB, Math.max(0.0, energyBLab - massB), momentumB));
    }

    private static ParticleSpecies recoilPartner(ParticleSpecies parent, ParticleSpecies daughter) {
        return switch (parent) {
            case PION_PLUS -> daughter == ParticleSpecies.ANTIMUON
                    ? ParticleSpecies.NEUTRINO_MU : ParticleSpecies.POSITRON;
            case PION_MINUS -> daughter == ParticleSpecies.MUON
                    ? ParticleSpecies.NEUTRINO_MU : ParticleSpecies.ELECTRON;
            case PION_NEUTRAL, KAON_NEUTRAL, URANIUM238 -> ParticleSpecies.PHOTON;
            case KAON_PLUS, KAON_MINUS -> ParticleSpecies.NEUTRINO_MU;
            default -> ParticleSpecies.PHOTON;
        };
    }

    /**
     * Neutron beta decay: n -> p + e- + anti-nu_e.
     *
     * <p>The electron energy is sampled from the allowed beta spectrum dN/dE ~ p E (Q-E)^2,
     * the neutrino mass is then fixed by four-momentum conservation.
     */
    private static void betaDecay(ParticleSpecies parent, double kineticMeV, Vec3 direction,
                                 Random random, List<Product> out) {
        double parentMass = parent.mass();
        double totalEnergy = kineticMeV + parentMass;
        double beta = Relativity.clampBeta(
                Math.sqrt(Math.max(0.0, totalEnergy * totalEnergy - parentMass * parentMass))
                        / totalEnergy);
        double gamma = totalEnergy / parentMass;
        double qValue = parentMass - Units.PROTON_MASS - Units.ELECTRON_MASS;
        Vec3 tangent = direction.normalise();

        for (int attempt = 0; attempt < 8; attempt++) {
            double electronEnergy = sampleBetaSpectrum(qValue, random);
            // neutrino system invariant mass from four-momentum conservation
            double mNeutrinoSquared = parentMass * parentMass - 2.0 * parentMass * electronEnergy
                    + Units.ELECTRON_MASS * Units.ELECTRON_MASS;
            if (mNeutrinoSquared <= 0) {
                continue;
            }
            double mNeutrino = Math.sqrt(mNeutrinoSquared);
            double electronMomentum = Math.sqrt(Math.max(0.0,
                    electronEnergy * electronEnergy - Units.ELECTRON_MASS * Units.ELECTRON_MASS));
            double cosTheta = random.nextDouble() * 2.0 - 1.0;
            double phi = random.nextDouble() * Math.PI * 2.0;
            Vec3[] basis = orthonormalBasis(tangent);
            Vec3 perpendicular = basis[0].scale(Math.cos(phi)).add(basis[1].scale(Math.sin(phi)));
            double parallel = gamma * (electronMomentum * cosTheta + beta * electronEnergy);
            double perpendicularMagnitude = electronMomentum * Math.sqrt(1 - cosTheta * cosTheta);
            Vec3 momentum = tangent.scale(parallel).add(perpendicular.scale(perpendicularMagnitude));
            double labEnergy = gamma * (electronEnergy + beta * electronMomentum * cosTheta);
            out.add(new Product(ParticleSpecies.ELECTRON,
                    Math.max(0.0, labEnergy - Units.ELECTRON_MASS), momentum));
            // the remaining invariant mass is shared by the antineutrino; the proton carries the
            // recoil opposite to the lepton pair.
            out.add(new Product(ParticleSpecies.PROTON,
                    Math.max(0.0, (gamma * (parentMass - electronEnergy) - mNeutrino * gamma)
                            + Units.PROTON_MASS * 0.0),
                    tangent.scale(-parallel).subtract(perpendicular.scale(perpendicularMagnitude))));
            out.add(new Product(ParticleSpecies.NEUTRINO_E,
                    Math.max(0.0, mNeutrino * (gamma - 1.0)),
                    tangent.scale(-parallel * 0.0)));
            return;
        }
    }

    /** dN/dE ~ sqrt(E^2 - m^2) * E * (Q - E)^2 shaped beta spectrum. */
    private static double sampleBetaSpectrum(double qValue, Random random) {
        double max = qValue * (0.6 + 0.4 * random.nextDouble());
        for (int i = 0; i < 24; i++) {
            double energy = Units.ELECTRON_MASS
                    + random.nextDouble() * (qValue - Units.ELECTRON_MASS);
            double p = Math.sqrt(Math.max(0.0,
                    energy * energy - Units.ELECTRON_MASS * Units.ELECTRON_MASS));
            double weight = p * energy * Math.pow(Math.max(0.0, qValue - energy), 2);
            double reference = Math.pow(Math.max(1.0e-9, qValue), 4) / 12.0;
            if (random.nextDouble() < weight / Math.max(1.0e-12, reference)) {
                max = energy;
                break;
            }
        }
        return Math.min(max, qValue);
    }

    /** Muon decay: mu -> e + nu_mu + anti-nu_e with the Michel spectrum. */
    private static void michelDecay(double kineticMeV, Vec3 direction, Random random,
                                    List<Product> out) {
        double parentMass = Units.MUON_MASS;
        double totalEnergy = kineticMeV + parentMass;
        double beta = Relativity.clampBeta(
                Math.sqrt(Math.max(0.0, totalEnergy * totalEnergy - parentMass * parentMass))
                        / totalEnergy);
        double gamma = totalEnergy / parentMass;
        double qValue = parentMass - Units.ELECTRON_MASS;

        // Michel spectrum: x = E_e / E_max, f(x) = 2x^2(3 - 2x) is a good approximation.
        double x = 0.0;
        do {
            x = random.nextDouble();
        } while (random.nextDouble() > 2.0 * x * x * (3.0 - 2.0 * x) / 1.08);
        double electronEnergy = Units.ELECTRON_MASS + x * (qValue - Units.ELECTRON_MASS);
        double electronMomentum = Math.sqrt(Math.max(0.0,
                electronEnergy * electronEnergy - Units.ELECTRON_MASS * Units.ELECTRON_MASS));

        Vec3 tangent = direction.normalise();
        Vec3[] basis = orthonormalBasis(tangent);
        double cosTheta = random.nextDouble() * 2.0 - 1.0;
        double phi = random.nextDouble() * Math.PI * 2.0;
        Vec3 perpendicular = basis[0].scale(Math.cos(phi)).add(basis[1].scale(Math.sin(phi)));
        double parallel = gamma * (electronMomentum * cosTheta + beta * electronEnergy);
        double perpMag = electronMomentum * Math.sqrt(Math.max(0.0, 1 - cosTheta * cosTheta));
        Vec3 momentum = tangent.scale(parallel).add(perpendicular.scale(perpMag));
        double labEnergy = gamma * (electronEnergy + beta * electronMomentum * cosTheta);
        out.add(new Product(ParticleSpecies.ELECTRON,
                Math.max(0.0, labEnergy - Units.ELECTRON_MASS), momentum));

        double neutrinoEnergy = (totalEnergy - labEnergy) * 0.5;
        Vec3 back = tangent.scale(-parallel).subtract(perpendicular.scale(perpMag));
        Vec3 backUnit = back.length() > 1.0e-9 ? back.normalise() : tangent.scale(-1.0);
        Vec3[] backBasis = orthonormalBasis(backUnit);
        double cos2 = random.nextDouble() * 2.0 - 1.0;
        double phi2 = random.nextDouble() * Math.PI * 2.0;
        Vec3 dir2 = backUnit.scale(cos2)
                .add(backBasis[0].scale(Math.sqrt(1 - cos2 * cos2) * Math.cos(phi2)))
                .add(backBasis[1].scale(Math.sqrt(1 - cos2 * cos2) * Math.sin(phi2)));
        out.add(new Product(ParticleSpecies.NEUTRINO_MU, neutrinoEnergy,
                dir2.scale(neutrinoEnergy)));
        out.add(new Product(ParticleSpecies.NEUTRINO_E, neutrinoEnergy,
                backUnit.scale(neutrinoEnergy)));
    }

    /** Charged kaon decay with the measured branching ratios. */
    private static void kaonDecay(ParticleSpecies parent, double kineticMeV, Vec3 direction,
                                  Random random, List<Product> out) {
        double roll = random.nextDouble();
        if (roll < 0.635) {
            twoBody(parent, kineticMeV, direction, random, Units.KAON_CHARGED_MASS,
                    parent == ParticleSpecies.KAON_PLUS ? ParticleSpecies.ANTIMUON
                            : ParticleSpecies.MUON, out);
        } else if (roll < 0.845) {
            twoBody(parent, kineticMeV, direction, random, Units.KAON_CHARGED_MASS,
                    ParticleSpecies.PION_NEUTRAL, out);
            // the neutral pion decays immediately into two photons
            if (!out.isEmpty()) {
                Product pion = out.remove(0);
                out.addAll(decay(ParticleSpecies.PION_NEUTRAL, pion.energyMeV(),
                        pion.momentum().normalise(), random));
            }
        } else if (roll < 0.90) {
            twoBody(parent, kineticMeV, direction, random, Units.KAON_CHARGED_MASS,
                    ParticleSpecies.PION_PLUS, out);
        } else {
            betaDecay(ParticleSpecies.NEUTRON, kineticMeV, direction, random, out);
        }
    }

    /** Builds an orthonormal basis around a direction. */
    public static Vec3[] orthonormalBasis(Vec3 direction) {
        Vec3 u = direction.normalise();
        Vec3 helper = Math.abs(u.y()) < 0.9 ? new Vec3(0, 1, 0) : new Vec3(1, 0, 0);
        Vec3 e1 = helper.cross(u).normalise();
        Vec3 e2 = u.cross(e1).normalise();
        return new Vec3[]{e1, e2};
    }
}
